//! Conformance vectors for the `ethos_collapse_whitespace_v1` normalization profile.
//!
//! More than one implementation of this profile exists across the estate: this
//! crate's `normalize_quote`, and JavaScript copies in consumers that hash
//! `expected_text` before verification. They have already drifted once — a JS copy
//! collapsed U+000B (vertical tab), which `char::is_ascii_whitespace` does not
//! include, so a sha256 computed on the producing side could disagree with the
//! verifier's recompute while both sides named the same profile.
//!
//! `schemas/normalization-vectors.json` is the profile's executable definition: an
//! implementation matches the verifier if and only if it maps every vector's input
//! to its output. Consumers vendor the file and run it in their own CI, so drift
//! fails a build instead of failing a verdict. The file is generated from
//! `normalize_quote` itself — never edited by hand — via:
//!
//! ```text
//! cargo test -p ethos-verify --test normalization_vectors -- --ignored
//! ```

use std::path::PathBuf;

use ethos_verify::{normalize_quote, normalize_quote_unicode_compat_v1};
use serde_json::{json, Value};

/// The wire name of the profile, as consumers declare it in
/// `text_normalization_profile` fields.
const PROFILE: &str = "ethos_collapse_whitespace_v1";

/// Vector inputs, each named for the rule it pins. The outputs are never written
/// here: they come from `normalize_quote`, so the file cannot disagree with the
/// implementation it documents.
fn vector_inputs() -> Vec<(&'static str, &'static str)> {
    vec![
        // The collapse set is exactly `char::is_ascii_whitespace`:
        // space, tab, line feed, form feed, carriage return.
        ("crlf-collapses-to-one-space", "a\r\nb"),
        ("bare-cr-collapses-to-one-space", "a\rb"),
        ("tab-run-collapses-to-one-space", "a\t\t b"),
        ("form-feed-collapses-to-one-space", "a\u{000C}b"),
        ("mixed-ascii-run-collapses-to-one-space", "a \t\n b"),
        // U+000B is NOT in the collapse set — the drift a JS copy shipped.
        ("vertical-tab-is-not-collapsed", "a\u{000B}b"),
        (
            "vertical-tab-survives-between-collapsed-spaces",
            "a \u{000B} b",
        ),
        // Trimming uses Unicode `White_Space`, a wider set than the collapse set,
        // so VT and NBSP survive inside a quote but not at its edges.
        ("vertical-tab-at-the-edges-is-trimmed", "\u{000B}a\u{000B}"),
        ("nbsp-is-not-collapsed", "a\u{00A0}b"),
        ("nbsp-at-the-edges-is-trimmed", "\u{00A0}a\u{00A0}"),
        ("unicode-line-separator-is-not-collapsed", "a\u{2028}b"),
        ("ideographic-space-is-not-collapsed", "a\u{3000}b"),
        ("ascii-edges-are-trimmed", "  a  "),
        ("empty-stays-empty", ""),
        ("whitespace-only-becomes-empty", " \t\r\n "),
        // Non-whitespace code points pass through untouched, whatever their width.
        ("emoji-passes-through", "a  \u{1F600}  b"),
        ("combining-mark-passes-through", "cafe\u{0301}  x"),
    ]
}

fn vectors_json() -> Value {
    json!({
        "profile": PROFILE,
        "implementation": "ethos-verify::normalize_quote",
        "description": "Executable definition of the profile: an implementation \
            conforms if and only if it maps every input to its output. Collapse runs \
            of ASCII whitespace (space, tab, LF, FF, CR — exactly Rust's \
            char::is_ascii_whitespace) to one space after normalizing line endings, \
            then trim Unicode White_Space from both ends. Generated by `cargo test \
            -p ethos-verify --test normalization_vectors -- --ignored`; never edited \
            by hand.",
        "vectors": vector_inputs()
            .into_iter()
            .map(|(name, input)| {
                json!({
                    "name": name,
                    "input": input,
                    "output": normalize_quote(input),
                })
            })
            .collect::<Vec<_>>(),
    })
}

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../schemas/normalization-vectors.json")
}

#[test]
fn vector_file_matches_normalize_quote() {
    let path = vectors_path();
    let on_disk: Value = serde_json::from_slice(
        &std::fs::read(&path).unwrap_or_else(|e| panic!("{} is readable: {e}", path.display())),
    )
    .expect("normalization-vectors.json parses");
    assert_eq!(
        on_disk,
        vectors_json(),
        "schemas/normalization-vectors.json disagrees with normalize_quote; \
         regenerate it with `cargo test -p ethos-verify --test normalization_vectors -- --ignored`"
    );
}

#[test]
#[ignore = "writes schemas/normalization-vectors.json from normalize_quote"]
fn regenerate_vector_file() {
    let mut bytes = serde_json::to_string_pretty(&vectors_json()).expect("vectors serialize");
    bytes.push('\n');
    std::fs::write(vectors_path(), bytes).expect("vector file is writable");
}

/// The wire name of the opt-in fold profile — the `text_normalization` config value.
const UNICODE_PROFILE: &str = "unicode_compat_v1";

/// Vector inputs for `unicode_compat_v1`, one per fold-table row plus the
/// whitespace edges. The vertical-tab vector is named to flag the deliberate
/// difference from `ethos_collapse_whitespace_v1`: this profile collapses every
/// Unicode whitespace character, so VT collapses here and survives there.
fn unicode_vector_inputs() -> Vec<(&'static str, &'static str)> {
    vec![
        ("curly-apostrophe-folds", "it\u{2019}s"),
        ("curly-double-quotes-fold", "\u{201C}quoted\u{201D}"),
        ("single-quote-family-folds", "\u{2018}a\u{201A}b\u{201B}c"),
        ("double-quote-family-folds", "\u{201E}a\u{201F}b"),
        ("en-dash-folds-to-hyphen", "2019\u{2013}2020"),
        ("em-dash-folds-to-hyphen", "a\u{2014}b"),
        ("minus-sign-folds-to-hyphen", "\u{2212}5"),
        (
            "remaining-dash-family-folds",
            "a\u{2010}b\u{2011}c\u{2012}d\u{2015}e",
        ),
        ("ellipsis-expands-to-three-dots", "a\u{2026}b"),
        ("ligature-ffi-expands", "e\u{FB03}cient"),
        ("ligature-fi-expands", "\u{FB01}nal"),
        ("ligature-fl-expands", "\u{FB02}ow"),
        (
            "remaining-ligatures-expand",
            "\u{FB00}\u{FB04}\u{FB05}\u{FB06}",
        ),
        ("soft-hyphen-is-erased", "evi\u{00AD}dence"),
        ("zero-width-space-is-erased", "a\u{200B}b"),
        ("bom-is-erased", "\u{FEFF}a"),
        ("nbsp-collapses-to-one-space", "a\u{00A0}\u{00A0}b"),
        ("ideographic-space-collapses", "a\u{3000}b"),
        ("vertical-tab-collapses-in-this-profile", "a\u{000B}b"),
        ("line-separator-collapses", "a\u{2028}b"),
        (
            "erased-char-inside-whitespace-yields-one-space",
            "a \u{00AD} b",
        ),
        ("edges-are-trimmed", " \u{00A0}a\u{2019} "),
        ("empty-stays-empty", ""),
        ("plain-ascii-is-untouched", "plain text"),
    ]
}

fn unicode_vectors_json() -> Value {
    json!({
        "profile": UNICODE_PROFILE,
        "implementation": "ethos-verify::normalize_quote_unicode_compat_v1",
        "description": "Executable definition of the opt-in unicode_compat_v1 \
            profile (the text_normalization config value of the same name): collapse \
            runs of Unicode whitespace (Rust's char::is_whitespace) to one ASCII \
            space, fold the pinned v1 table of Unicode lookalikes to ASCII — curly \
            quotes, the dash family, common Latin ligatures, U+2026; soft hyphen, \
            zero-width space, and U+FEFF erased — and trim. The table is versioned \
            by the profile name and never edited. Generated by `cargo test -p \
            ethos-verify --test normalization_vectors -- --ignored`; never edited by \
            hand.",
        "vectors": unicode_vector_inputs()
            .into_iter()
            .map(|(name, input)| {
                json!({
                    "name": name,
                    "input": input,
                    "output": normalize_quote_unicode_compat_v1(input),
                })
            })
            .collect::<Vec<_>>(),
    })
}

fn unicode_vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../schemas/normalization-vectors-unicode-compat-v1.json")
}

#[test]
fn unicode_vector_file_matches_normalize_quote_unicode_compat_v1() {
    let path = unicode_vectors_path();
    let on_disk: Value = serde_json::from_slice(
        &std::fs::read(&path).unwrap_or_else(|e| panic!("{} is readable: {e}", path.display())),
    )
    .expect("normalization-vectors-unicode-compat-v1.json parses");
    assert_eq!(
        on_disk,
        unicode_vectors_json(),
        "schemas/normalization-vectors-unicode-compat-v1.json disagrees with \
         normalize_quote_unicode_compat_v1; regenerate it with `cargo test -p \
         ethos-verify --test normalization_vectors -- --ignored`"
    );
}

#[test]
#[ignore = "writes schemas/normalization-vectors-unicode-compat-v1.json from its implementation"]
fn regenerate_unicode_vector_file() {
    let mut bytes =
        serde_json::to_string_pretty(&unicode_vectors_json()).expect("vectors serialize");
    bytes.push('\n');
    std::fs::write(unicode_vectors_path(), bytes).expect("vector file is writable");
}
